# Notebook ,nginx and CV access
#
# Access via "http://localhost:80" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# Create OD container
object_detection:
  image: object-detection-image
  container_name: object_detection
  restart: always
  environment:
     - TERM=xterm
  hostname: '127.0.0.1'
  ports:
     - "81:80"             #http
     - "8080:8080"         #JupyterNB
     - "443:443"           #https
    #- "8022:22"           #ssh
    #- "8025:25"           #smtp
    #- "8143:143"          #g-imap
    #- "8587:587"          #g-smtp
    #- "8432:5432"         #postgres
    #- "8000:8000"         #dev
    #- "8017:27017"        #mongodb
    #- "8080:8080"         #JupyterNB
  volumes:
      #Volume moutning for image entry
    - /home/felixbarros/Develoment/Projects/object_detection/Version_1/CV/js_face_recognition.html:/usr/share/nginx/html/index.html
    - /home/felixbarros/Develoment/Projects/object_detection/Version_1/CV/opencv.js:/usr/share/nginx/html/opencv.js
    - /home/felixbarros/Develoment/Projects/object_detection/Version_1/CV/utils.js:/usr/share/nginx/html/utils.js



  
